/**
 * Specimen-page generator — turns a compiled design system into ONE self-contained
 * HTML document (P3 of the mature-default-DS initiative). Pure string transform:
 * no filesystem, no network, no model. Same DS → byte-identical output (no timestamps
 * in the body; only the deterministic generation + registry hash appear).
 *
 * Every section renders from REAL data:
 *  - `:root` tokens via emitCss (the css target — reused, never duplicated).
 *  - Color paired roles enumerated by inferForegroundPairs; each swatch renders its
 *    OWN declared foreground, so the contrast you see is the contract the compiler seals.
 *  - Unpaired structural roles (border/input/ring) + the chart-1..5 row when present.
 *  - Type ramp from the font-size scale; radius/elevation/duration chips from the tree.
 *  - One block per registry record WITH markup (the registry is the ONLY component
 *    source — the preview never authors component markup); name-only records are listed.
 *  - Header pair-count + min-ratio come from the ds-a11y core (called in-process).
 *
 * The section builders live in ds-preview-sections.ts; this module owns only assembly.
 */
import { emitCss } from "./token-emit.js";
import { checkTokenContrast } from "./ds-a11y.js";
import { SPECIMEN_CHROME_CSS } from "./ds-preview-chrome.js";
import {
  esc, colorSection, typeSection, shapeSection, motionSection, componentsSection,
} from "./ds-preview-sections.js";
import type { DesignSystem } from "./design-system.js";
import type { ResolvedToken } from "./token-model.js";

export interface SpecimenModel {
  html: string;
  /** Component records rendered as a markup block (the page's showcased count). */
  components: number;
  /** Declared text×surface pairs checked (from the ds-a11y core). */
  pairs: number;
  bytes: number;
}

/**
 * Build the self-contained specimen HTML for a loaded design system.
 * Deterministic: identical DS input yields byte-identical output.
 */
export function buildSpecimenPage(ds: DesignSystem): SpecimenModel {
  const byPath = new Map<string, ResolvedToken>(ds.resolved.map((t) => [t.path, t]));
  const a11y = checkTokenContrast(ds.resolved);
  const ratioByPair = new Map(a11y.pairs.map((p) => [`${p.text}|${p.surface}`, p.ratio]));
  const minRatio = a11y.pairs.length > 0 ? a11y.pairs[0]?.ratio : undefined;

  const m = ds.manifest;
  const badge =
    a11y.checkedPairs > 0 && minRatio !== undefined
      ? `<span class="badge-aa">paired AA &mdash; ${a11y.checkedPairs} pairs &middot; ${a11y.failures.length} failures &middot; min ${minRatio}:1</span>`
      : `<span class="meta">no paired colour roles detected</span>`;

  const header =
    `  <header>\n` +
    `    <p class="kicker">${esc(m.name)} &middot; Design System Specimen</p>\n` +
    `    <h1>${esc(m.name)}</h1>\n` +
    `    <p class="meta" style="margin-top:10px">generation ${m.generation} &middot; persona <strong>${esc(m.persona.slug)}</strong> &middot; ${ds.resolved.length} tokens &middot; ${badge}</p>\n` +
    `    <p class="lead">${esc(m.intent)}</p>\n` +
    `  </header>`;

  const comps = componentsSection(ds.registry.components);
  const shortHash = m.registryHash.replace(/^sha256-/, "").slice(0, 12);
  const footer =
    `  <footer class="foot">\n` +
    `    <p class="meta">Generated by <code>ui ds preview</code> from the compiled design system &middot; registry ${esc(shortHash)}</p>\n` +
    `  </footer>`;

  const html =
    `<!doctype html>\n` +
    `<html lang="en">\n` +
    `<head>\n` +
    `<meta charset="utf-8">\n` +
    `<meta name="viewport" content="width=device-width, initial-scale=1">\n` +
    `<title>${esc(m.name)} &mdash; Design System Specimen</title>\n` +
    `<style>\n` +
    emitCss(ds.resolved) +
    SPECIMEN_CHROME_CSS +
    `</style>\n` +
    `</head>\n` +
    `<body>\n` +
    `<main>\n` +
    header + `\n` +
    colorSection(byPath, ratioByPair) + `\n` +
    typeSection(ds.resolved) + `\n` +
    shapeSection(ds.resolved) + `\n` +
    motionSection(ds.resolved) + `\n` +
    comps.html + `\n` +
    footer + `\n` +
    `</main>\n` +
    `</body>\n` +
    `</html>\n`;

  return { html, components: comps.rendered, pairs: a11y.checkedPairs, bytes: Buffer.byteLength(html, "utf8") };
}
