// Build the bundles: walker-bundle (a CLI source artifact), cli, plugin-main
// (code.js), plugin-ui (ui.html).
// Usage: node scripts/build.mjs [walker-bundle|cli|plugin-main|plugin-ui|all] [--watch]
import * as esbuild from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const target = process.argv[2] ?? 'all';
const watch = process.argv.includes('--watch');

const common = { bundle: true, target: 'es2020', logLevel: 'info' };

/**
 * The reverse-walker (plugin/src/main/scan-node.ts + its sub-walkers) bundled into a
 * self-contained IIFE STRING and emitted as a CLI source module.
 *
 * Why build-time and not runtime: `scan-node` injects this walker into the plugin
 * sandbox via EXEC_JS. Bundling it when the command runs would need the plugin/src
 * checkout AND esbuild on the box — neither exists on a dist-only install, so the
 * mirror could never close there. Emitting it as a plain string constant makes the
 * CLI bundle self-contained. It stays drift-free with the unit-tested walker because
 * it IS that source, bundled — and tests/scan-node-walker-bundle.test.ts fails if the
 * committed artifact is stale.
 */
async function buildWalkerBundle() {
  const res = await esbuild.build({
    ...common,
    entryPoints: [resolve(root, 'plugin/src/main/scan-node.ts')],
    platform: 'browser', // Figma sandbox: no node APIs
    format: 'iife',
    globalName: '__scan',
    write: false,
  });
  const header = '// GENERATED by scripts/build.mjs — do not edit; run `npm run build`.\n'
    + '// The plugin/src/main/scan-node.ts walker, bundled into an IIFE exposing `__scan`.\n'
    + '// scan-node.ts injects this into the plugin sandbox, so a dist-only install needs\n'
    + '// no repo checkout. Drift-guarded by tests/scan-node-walker-bundle.test.ts.\n';
  const out = `${header}export const SCAN_NODE_WALKER_BUNDLE = ${JSON.stringify(res.outputFiles[0].text)};\n`;
  mkdirSync(resolve(root, 'cli/src/generated'), { recursive: true });
  writeFileSync(resolve(root, 'cli/src/generated/scan-node-walker-bundle.ts'), out);
}

async function buildCli() {
  await buildWalkerBundle(); // a CLI source file — must be fresh before the CLI bundle
  await esbuild.build({
    ...common,
    entryPoints: [resolve(root, 'cli/src/figma-agent.ts')],
    platform: 'node',
    format: 'esm',
    outfile: resolve(root, 'cli/dist/figma-agent.js'),
    banner: { js: '#!/usr/bin/env node' },
    // ws + the capture-only optional deps stay external (resolved at runtime;
    // playwright is heavy + has native deps and must not be inlined).
    external: ['ws', 'playwright', 'playwright-core', 'puppeteer-core', 'pixelmatch', 'pngjs'],
  });
}

async function buildPluginMain() {
  await esbuild.build({
    ...common,
    entryPoints: [resolve(root, 'plugin/src/main/main.ts')],
    platform: 'browser', // Figma plugin sandbox: no node APIs
    format: 'iife',
    outfile: resolve(root, 'plugin/code.js'),
  });
}

async function buildPluginUi() {
  const res = await esbuild.build({
    ...common,
    entryPoints: [resolve(root, 'plugin/src/ui/ui-relay.ts')],
    platform: 'browser',
    format: 'iife',
    write: false,
  });
  const js = res.outputFiles[0].text;
  // The panel chrome is authored in plugin/src/ui/panel.html — the SOURCE the P2
  // 4-linter gate lints (tests/figma-plugin-panel.test.ts). The build only inlines
  // the compiled relay+panel bundle at the marker so ui.html stays one self-contained
  // file. A function replacer avoids `$`-pattern interpretation in the bundle text.
  const MARKER = '/*__FIGMA_AGENT_UI_BUNDLE__*/';
  const template = readFileSync(resolve(root, 'plugin/src/ui/panel.html'), 'utf8');
  if (!template.includes(MARKER)) {
    throw new Error(`plugin/src/ui/panel.html is missing the ${MARKER} bundle marker`);
  }
  const html = template.replace(MARKER, () => js);
  mkdirSync(resolve(root, 'plugin'), { recursive: true });
  writeFileSync(resolve(root, 'plugin/ui.html'), html);
}

const jobs = {
  'walker-bundle': buildWalkerBundle,
  cli: buildCli,
  'plugin-main': buildPluginMain,
  'plugin-ui': buildPluginUi,
};
// `all` omits walker-bundle on purpose: buildCli regenerates it as its prerequisite.
const ALL = ['cli', 'plugin-main', 'plugin-ui'];
if (target === 'all') {
  for (const t of ALL) await jobs[t]();
} else if (jobs[target]) {
  await jobs[target]();
} else {
  console.error(`unknown target: ${target}`);
  process.exit(1);
}
if (watch) console.log('(watch mode not implemented in spike — rerun to rebuild)');
